version: 2
updates:
  # GitHub Actions の設定
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Node.js (npm) の設定
  - package-ecosystem: "npm"
    directory: "/next"
    schedule:
      interval: "daily"

  # Ruby (Bundler) の設定
  - package-ecosystem: "bundler"
    directory: "/rails"
    schedule:
      interval: "daily"