changelog:
  categories:
    - title: Enhancements
      labels:
        - enhancement
    - title: Bug Fixes
      labels:
        - bug
        - fixes
    - title: Breaking Changes
      labels:
        - breaking-change
