FROM node:18-alpine
RUN ls -la

ARG PACKAGES="alpine-sdk vim"

RUN apk update \
  && apk upgrade \
  && apk add --update --no-cache $PACKAGES

WORKDIR /usr/app
COPY package*.json ./
RUN npm install
CMD ["npm", "run", "dev"]