# この設定は2024-07-14 09:24:12 UTCにRuboCop バージョン1.65.0を使用して
# `rubocop --auto-gen-config`によって生成されました。
# コードベースから違反が取り除かれるにつれて、ユーザーがこれらの設定を
# 一つずつ削除していくことが目的です。
# 検査されたコードの変更やRubocopの新しいバージョンのインストールにより、
# このファイルを再生成する必要がある場合があることに注意してください。

# 違反数: 1
# 空のブロックがあります
Lint/EmptyBlock:
  Exclude:
    - 'spec/factories/tests.rb'

# 違反数: 1
# RSpecのテストで実際の値をexpectしていません
RSpec/ExpectActual:
  Exclude:
    - 'spec/models/test_spec.rb'

# 違反数: 1
# RSpecのテストで同一の値を比較しています
RSpec/IdenticalEqualityAssertion:
  Exclude:
    - 'spec/models/test_spec.rb'

# 違反数: 1
# RSpecのテストで検証されていないdoubleを使用しています
RSpec/VerifiedDoubles:
  Exclude:
    - 'spec/models/test_spec.rb'