# ベースイメージとして、Ruby 3.1.5のslimバージョンを使用。通常イメージより小さく、必要最小限の内容
FROM ruby:3.1.5-slim

# 必要なパッケージのインストール
RUN apt-get update -qq && \
    apt-get install -y --no-install-recommends \
    build-essential \
    default-libmysqlclient-dev \
    vim \
    && rm -rf /var/lib/apt/lists/*

# アプリケーションディレクトリの作成
WORKDIR /app

# Gemfile と Gemfile.lock をコピー
COPY Gemfile Gemfile.lock ./

# Bundlerをインストールし、development と test 環境の gem を除外する
# 本番環境用の gem をインストールする
# --jobs 4: 4つの並列ジョブでインストールを高速化
# --retry 3: 失敗時に3回までリトライ
RUN gem install bundler && \
    bundle config set without 'development test' && \
    bundle install --jobs 4 --retry 3

# アプリケーションのソースコードをコピー
COPY . .

# セキュリティ強化のため、非root権限のユーザー（appuser）を作成し、
# アプリケーションディレクトリの所有者に設定します。
# 以降の操作をこのユーザーで実行するように切り替える。
RUN useradd -m appuser && chown -R appuser:appuser /app
USER appuser

# エントリーポイントスクリプトをコンテナにコピーし、実行権限を付与。
# 起動時エントリーポイントとして設定。
COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]

# Puma を使用して Rails サーバーを起動
CMD ["bundle", "exec", "rails", "server", "-p", "3000"]

EXPOSE 3000
