name: Auto Draft Release

on:
  push:
    branches:
      # プロダクションブランチにプッシュされたときに実行
      - production
  pull_request_target:
    types: [opened, reopened, synchronize, edited]
  workflow_dispatch:

# パイプエラーが拾えるので、機械的に追加
defaults:
  run:
    shell: bash

# 同一グループのワークフローが多重起動しないように設定
# 同プルリクエストで複数ワークフローが起動した場合に、古いワークフローをキャンセルする
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# トークンのパーミッションを明示的に設定
permissions:
  contents: write
  pull-requests: write

jobs:
  draft-release:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get latest release
        id: get_latest_release
        run: |
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "latest_tag=${latest_tag}" >> $GITHUB_OUTPUT

      - name: Auto-generate release notes
        id: release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config-name: release.yml
          version: ${{ steps.get_latest_release.outputs.latest_tag }}

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.release.outputs.tag_name }}
          release_name: Release ${{ steps.release.outputs.tag_name }}
          body: ${{ steps.release.outputs.body }}
          draft: true
          prerelease: false
