name: auto-merge
on:
  pull_request:
jobs:
  merge:
    # dependabotからのプルリクエストのみで実行
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write # マージするブランチの内容を書き込み
      pull-requests: write # マージするブランチをマージ
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GITHUB CLIのクレデンシャル
    steps:
      - uses: actions/checkout@v4
      - id: meta # 依存関係のメタデータを取得
        uses: dependabot/fetch-metadata@v2
      # パッチバージョンの更新時にマージ
      # 開発者向けの依存関係の更新かつ、マイナーバージョンの更新でなければマージ
      # github_actionの更新かつ、マイナーバージョンの更新でなければマージ
      - if: >-
          steps.meta.outputs.update-type == 'version-update:semver-patch' ||
          (steps.meta.outputs.dependency-type == 'direct:development' && steps.meta.outputs.update-type != 'version-update:semver-major') ||
          (steps.meta.outputs.package-ecosystem == 'github_actions' && steps.meta.outputs.update-type != 'version-update:semver-major')
        # GITHUB_CLIでマージ ステータスチェック完了し、すべて成功している場合マージ
        run: |
          gh pr review "${GITHUB_HEAD_REF}" --approve
          gh pr merge "${GITHUB_HEAD_REF}" --merge  --auto
