name: Greetings
on:
  workflow_dispatch:
    inputs:
      greeting:
        type: string
        default: Hello
        required: true
        description: input word

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.greeting }}"
