name: Verify Workflow

on:
  push:
    branches: [production, develop]
    paths:
      - ".github/workflows/**"
  pull_request:
    branches: [production, develop]
    paths:
      - ".github/workflows/**"
  workflow_dispatch:

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: current directory
        run: |
          pwd
          echo "current dierectory detail"
          ls -la

      - name: Debug directory structure
        run: |
          pwd
          ls -R ${{ github.workspace }}

      - name: Run actionlint
        working-directory: ${{ github.workspace }}
        run: |
          docker run --rm -v ${{ github.workspace }}:/repo rhysd/actionlint:latest -color
