name: Verify Next.js

on:
  push:
    branches: [production, develop]
    paths:
      - "next/**"
  pull_request:
    branches: [production, develop]
    paths:
      - "next/**"

# パイプエラーが拾えるので、機会的に追加
defaults:
  run:
    shell: bash

# 同一グループのワークフローが多重起動しないように設定
# 同プルリクエストで複数ワークフローが起動した場合に、古いワークフローをキャンセルする
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify-next:
    runs-on: ubuntu-latest
    timeout-minutes: 5 # すべてのワークフローで書くと良い
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug - Print current directory
        run: pwd

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: next/my-app/package-lock.json

      - name: Output versions
        run: |
          node -v
          npm -v

      - name: Install dependencies
        working-directory: next/my-app
        run: npm ci

      - name: Run test
        working-directory: next/my-app
        run: npm run test

      - name: Run TypeScript compiler
        working-directory: next/my-app
        run: npm run lint

      - name: Check formatting
        working-directory: next/my-app
        run: npm run format
