name: Verify Next.js

on:
  push:
    branches: [production, develop]
    paths:
      - "next/**"
  pull_request:
    branches: [production, develop]
    paths:
      - "next/**"

jobs:
  verify-next:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: next/my-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ../package-lock.json

      - name: Install dependencies
        run: |
          npm ci

      - name: Run test
        run: |
          echo "npm run test テストを作成後はここに記述"
